services:
  channels:
    build:
      context: .
      dockerfile: channels/Dockerfile
    image: service-channels:latest
    ports:
      - "8080:8080"
  posts:
    build:
      context: .
      dockerfile: posts/Dockerfile
    image: service-posts:latest
    ports:
      - "8081:8081"
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: my_database
    volumes:
      - sv_files:/data/files
  subscriptions:
    build:
      context: .
      dockerfile: subscriptions/Dockerfile
    image: service-subscriptions:latest
    ports:
      - "8082:8082"
  users:
    build:
      context: .
      dockerfile: users/Dockerfile
    image: service-users:latest
    ports:
      - "8083:8083"
  mysql:
    build:
      context: ./database
      dockerfile: Dockerfile
    container_name: sv_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: study_vault
      MYSQL_USER: sv_user
      MYSQL_PASSWORD: 123456
    ports:
      - "6609:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
    driver: local
  sv_files:
    driver: local
