services:
  channels:
    build:
      context: .
      dockerfile: channels/Dockerfile
    ports:
      - "8080:8080"
  posts:
    build:
      context: .
      dockerfile: posts/Dockerfile
    ports:
      - "8081:8081"
  subscriptions:
    build:
      context: .
      dockerfile: subscriptions/Dockerfile
    ports:
      - "8082:8082"
  users:
    build:
      context: .
      dockerfile: users/Dockerfile
    ports:
      - "8083:8083"
  mysql:
    image: sv_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: study_vault
    ports:
      - "6609:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
    driver: local
  sv_files:
    driver: local
